spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: aiagent
  profiles:
    active: local
  ai:
    dashscope:
      ollama:
        base-url: http://localhost:11434
        chat:
          model: gemma3:1b
      api-key: sk-46fbc0fa35244024a77bf28fa151afe1
      chat:
        options:
          model: qwen-plus
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        initialize-schema: true


  datasource:
    url: jdbc:postgresql://pgm-bp10m59b04p05c455o.rwlb.rds.aliyuncs.com:5432/love_agent
    username: lzz
    password: lzz010213!


server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yupi.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: H1XQQ6SsF9rzPhzKwcxG1Zdg

